config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :carts
  resources :cart_items

  resources :books do
    member do
      post :add_to_cart
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :books, through: :cart_items

  def add_book_to_cart(book)
    ci = cart_items.build
    ci.book = book
    ci.save
  end

  def total_price
    sum = 0
    amount = 0
    kind = cart_items.count

    cart_items.each do |cart_item|
      amount += cart_item.quantity
    end

    if kind == 1
      sum = amount * 100
    elsif kind == 2
      sum = amount * 100 - kind * 100 * 0.05
    elsif kind == 3
      sum = amount * 100 - kind * 100 * 0.1
    elsif kind == 4
      sum = amount * 100 - kind * 100 * 0.2
    elsif kind == 5
      sum = amount * 100 - kind * 100 * 0.25
    end
    sum
  end

  # def total_price(amount, kind)
  #   sum = 0
  #   if kind == 1
  #     sum = amount * 100
  #   elsif kind == 2
  #     sum = amount * 100 - kind * 100 * 0.05
  #   elsif kind == 3
  #     sum = amount * 100 - kind * 100 * 0.1
  #   elsif kind == 4
  #     sum = amount * 100 - kind * 100 * 0.2
  #   elsif kind == 5
  #     sum = amount * 100 - kind * 100 * 0.25
  #   end
  #   puts "#{amount}本书, #{kind}种, 总计$#{sum}."
  #   sum
  # end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_cart

  def current_cart
    @current_cart ||= find_cart
  end

  private

  def find_cart
    cart = Cart.find_by(id: session[:cart_id])
    if cart.blank?
      cart = Cart.create
    end
    session[:cart_id] = cart.id
    return cart
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def add_to_cart
    @book = Book.find(params[:id])
    if !current_cart.books.include?(@book)
      current_cart.add_book_to_cart(@book)
      flash[:notice] = "成功加入购物车"
    else
      flash[:warning] = "你的购物车内已有此物品"
    end
    redirect_to :back
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def update
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(book_id: params[:id])
    @cart_item.update(cart_item_params)
    redirect_to carts_path
  end

  def destroy
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(book_id: params[:id])
    @book = @cart_item.book
    @cart_item.destroy
    flash[:warning] = "已删除"
    redirect_to :back
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/views/books/index.html.erb
<div class="col-md-12">
  <table class="table table-hover">
    <thead>
      <tr>
        <td>Series</td>
        <td>Price</td>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.series %></td>
          <td>$<%= book.price %></td>
          <td>
            <%= link_to("加入购物车", add_to_cart_book_path(book),
                        method: :post, class: "btn btn-default") %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Series</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>操作选项</th>
        </tr>
      </thead>

      <tbody>
        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td><%= cart_item.book.series %></td>
            <td><%= cart_item.book.price %></td>
            <td>
              <%= form_for cart_item, url: cart_item_path(cart_item.book_id) do |f| %>
                <%= f.select :quantity, [0,1,2,3,4,5,6] %>
                <%= f.submit "更新", data: { disable_with: "Submiting..." }, class: "btn btn-xs btn-default" %>
              <% end %>
            </td>
            <td>
              <%= link_to("delete", cart_item_path(cart_item.book_id), method: :delete,
                          class: "btn btn-xs btn-default") %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <div class="total clearfix">
      <span class="pull-right">
         <span><h1>总计 $<%= render_cart_total_price(current_cart) %></h1></span>
      </span>
    </div>

    <hr>

    <div class="checkout clearfix">
      <%= link_to("确认结账", "#", class: "btn btn-default pull-right") %>
    </div>
  </div>
</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Harry Potter</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                  <%= link_to carts_path do %>
                    购物车 ( <%= current_cart.books.count %> )
                  <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HarryPotter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>